stages:
  - deploy

deploy:
  stage: deploy
  except:
    - tags
  tags: 
    - docker
  image: skandyla/fpm
  script: |
    # SSH
    mkdir ~/.ssh
    echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
    echo "$DEPLOY_SSH_ID" >> ~/.ssh/known_hosts

    # Remove old packages
    rm *.deb

    # Create package
    ./scripts/makedeb.sh

    # Puts the name of the latest package into a variable
    pkg=$(find pkg -name '*.deb' -printf '%P\n' | head -n 1)

    # Copies package to target server
    # If you have a self hosted apt source, use that.
    scp "$pkg" "DEPLOY_HOST":/tmp && ssh $DEPLOY_HOST "sudo apt update && sudo apt install ./$pkg"
